/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as EscalasRouteImport } from './routes/escalas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as AdvertenciasRouteImport } from './routes/advertencias'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalasRoute = EscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertenciasRoute = AdvertenciasRouteImport.update({
  id: '/advertencias',
  path: '/advertencias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertencias': typeof AdvertenciasRoute
  '/casos': typeof CasosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/escalas': typeof EscalasRoute
  '/membros': typeof MembrosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertencias': typeof AdvertenciasRoute
  '/casos': typeof CasosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/escalas': typeof EscalasRoute
  '/membros': typeof MembrosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertencias': typeof AdvertenciasRoute
  '/casos': typeof CasosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/escalas': typeof EscalasRoute
  '/membros': typeof MembrosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertencias'
    | '/casos'
    | '/configuracoes'
    | '/escalas'
    | '/membros'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertencias'
    | '/casos'
    | '/configuracoes'
    | '/escalas'
    | '/membros'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/advertencias'
    | '/casos'
    | '/configuracoes'
    | '/escalas'
    | '/membros'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertenciasRoute: typeof AdvertenciasRoute
  CasosRoute: typeof CasosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EscalasRoute: typeof EscalasRoute
  MembrosRoute: typeof MembrosRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalas': {
      id: '/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof EscalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertencias': {
      id: '/advertencias'
      path: '/advertencias'
      fullPath: '/advertencias'
      preLoaderRoute: typeof AdvertenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertenciasRoute: AdvertenciasRoute,
  CasosRoute: CasosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EscalasRoute: EscalasRoute,
  MembrosRoute: MembrosRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
